### ISSUE TITLE
End-to-End Testing

### ISSUE THREAD

**Issue by john-fike** [msudesigncpr/slate-ui#2]
- Different names of petri dishes than default
- Different dwell times than default
- Edges of petri dishes
- Colonies near x-coord OOB
- LB Agar
- Many small colonies (eh)
- "[Hazy](https://github.com/msudesigncpr/slate-ui/issues/2#issuecomment-2059828816)" Petri dishes
- different voltages on LED power supply
- False positives
- Doublets
- Save excel output

**Comment by john-fike** [comment]
We need to figure out what the right exposure setting is for both LB and MacConkey agar so that stuff isn't washed out or too dark. 

LB tends to make the center incredibly bright unless both the LED intensity and exposure are perfect. 

Camera is initialized [here](https://github.com/msudesigncpr/slate-ui/blob/b9b4d9cf43f448a9027532bd028ca4dd8efafabc/src/slate_ui/process_control.py#L150-L160)


The workflow for changing stuff in libmotorctrl is:
on your machine: clone into libmotorctrl, change, commit, push
on the cpr machine, in ```...Documents/slate-ui```: 
- ctrl + D
- ```hatch env prune```
- ```hatch shell```
- ```python src/slate_ui/slate.ui```

**Comment by john-fike** [comment]
### Hazy Petri Dishes

Beginning end-to-end tests. On petri dishes that are "hazy", we are seeing a miss near the edges of petri dishes. An example of a hazy dish:

<p align="center">
<img src="https://github.com/msudesigncpr/slate-ui/assets/80931988/975366a3-a368-4d35-a3c1-b28c92bd8672" width="300">
</p>


For now, I have disabled the removal of invalid/extra colonies, and the well plate number annotations. 
For the most part, we are dead on, however, there are a number of erroneous predictions apparent that don't happen in "normal" petri dishes. However, when this happens, cfu usually thinks its a bunch of tiny colonies near one another, so they all get obliterated by by either the minimum colony radius or minimum colony distance thresholds. There are also 3-4 doublet colonies that have been detected as a single colony. This is, again, worse than in non-hazy dishes. But should not be bad enough to put us out-of-spec.
I also have a hunch that the reflections on the shiny agar from the lights in the design lab are not helping.

The problems continue.
We are missing in the x-direction on picks that are near the edge of the petri dish. Will and I believe it is a bad x gsd, and are working to change it. I believe commit [d35db](https://github.com/msudesigncpr/libcolonyfind/commit/d35db45c78292271355af94ca4b99fc1e6dc4cb5) changes this gsd to one that works, but we are still working on testing.

**Comment by john-fike** [comment]
Turns out this "haze" is some kind of byproduct of... fermentation...(?). Cool I guess.

**Comment by john-fike** [comment]
### Different petri dish names than default

It looks like the UI never saves the names of petri dishes. They are set to "P{whatever}" during proc control init and never changed again. I don't see where they are read in in main_window but I could be missing it. 
However, it doesn't explode if you try to use different names, they are just thrown into the void. 
@w-culhane 


Process control init sets all petri dish names [here](https://github.com/msudesigncpr/slate-ui/blob/7dab2111c0d94733a4d88b2b957989dd40b44ef7/src/slate_ui/process_control.py#L74-L87). These names should be the names parsed when the proc control worker is instantiated [here](https://github.com/msudesigncpr/slate-ui/blob/7dab2111c0d94733a4d88b2b957989dd40b44ef7/src/slate_ui/main_window.py#L168-L172). [These values](https://github.com/msudesigncpr/slate-ui/blob/7dab2111c0d94733a4d88b2b957989dd40b44ef7/src/slate_ui/main_window.py#L72-L81) are what should be used to init proc control worker.

These names are what the images get saved as, and libcolonyfind treats these filenames as names, so they need to be somewhat clean (no slashes, periods, stuff like that). That can be considered later, but must be changed before handoff.

**Comment by w-culhane** [comment]
> ### Different petri dish names than default
> 
> It looks like the UI never saves the names of petri dishes. They are set to "P{whatever}" during proc control init and never changed again. I don't see where they are read in in main_window but I could be missing it. However, it doesn't explode if you try to use different names, they are just thrown into the void. @w-culhane
> 
> Process control init sets all petri dish names [here](https://github.com/msudesigncpr/slate-ui/blob/7dab2111c0d94733a4d88b2b957989dd40b44ef7/src/slate_ui/process_control.py#L74-L87). These names should be the names parsed when the proc control worker is instantiated [here](https://github.com/msudesigncpr/slate-ui/blob/7dab2111c0d94733a4d88b2b957989dd40b44ef7/src/slate_ui/main_window.py#L168-L172). [These values](https://github.com/msudesigncpr/slate-ui/blob/7dab2111c0d94733a4d88b2b957989dd40b44ef7/src/slate_ui/main_window.py#L72-L81) are what should be used to init proc control worker.
> 
> These names are what the images get saved as, and libcolonyfind treats these filenames as names, so they need to be somewhat clean (no slashes, periods, stuff like that). That can be considered later, but must be changed before handoff.

Names are applied as of e5bcb1596b2c1c5debc2fe2c6da303dfb08487ea. Name sanitization is a stretch goal T, but given the end users are trained technical people, hopefully we can trust them not to put silly symbols in their names.

For name sanitization, I think we can use [validators](https://doc.qt.io/qt-6/qlineedit.html#setValidator).

**Comment by john-fike** [comment]
If validators prove buggy I'm not opposed to replacing any bad names with default names (P{whatever})

**Comment by w-culhane** [comment]
We hit almost every colony (>95%) on the test dishes after the GSD fix. Names are validated, although there are some small things to fix there.

This issue is pretty general and seems mostly resolved. We can open smaller, separate issues for anything still unfixed.
