### ISSUE TITLE
Misc. Debugging

### ISSUE THREAD

**Issue by john-fike** [msudesigncpr/slate-ui#3]
- [x] Weird pause after sterilizing (WONTFIX)
- [x] Terminal window opening and closing every time `WSL` is used
- [x] Crashes after stop is hit too fast
- [x] Sanitize name strings
- [ ] UI continues updating after stop if stopped during movement/long delay (which can lead to crash if started again too fast)
- [ ] Add much more logging
- [x] Set idle needle position to be over terrorizer

**Comment by w-culhane** [comment]
Crash is no longer present.

**Comment by w-culhane** [comment]
Annoying terminal windows appearing fixed in https://github.com/msudesigncpr/libcolonyfind/commit/7fae1be3d5dbb55c808dafe743e1c98096766254

**Comment by w-culhane** [comment]
# Hello my name is william culhnahae i build slow code that runs slowly 

Pause during cooling is due to delays in how libmotorctrl works (lots of polling) so it can't really be fixed easily. The delay is mitigated somewhat by https://github.com/msudesigncpr/libmotorctrl/commit/05814abbf220dabb11f3b5ff43530c4054de48cb. If it's a serious problem it could be mitigated further by subtracting a second or so from the time entered by the user. This issue is WONTFIX for now.

**Comment by w-culhane** [comment]
Petri dish names are forced alphanumeric as of 1bd3a5e1f88e485beeecc5e8e581845ca74ceaf0. It will still happily accept empty or duplicate name fields, which leads to trouble.

**Comment by john-fike** [comment]
For empty entries, would 
`QRegularExpression("[a-zA-Z0-9]+")`
reject them? I [think](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Cheatsheet#quantifiers) + forces an appearance of at least something that matches a-zA-Z0-9 

For duplicate names, could we do this:
```python
if len(petri_dish_names) != len(set(petri_dish_names)): 
     petri_dish_names = [f"P{num}-{name}" for num, name in enumerate(petri_dish_names, 1)]
```

Before we create the petri dish objects [here](https://github.com/msudesigncpr/slate-ui/blob/1bd3a5e1f88e485beeecc5e8e581845ca74ceaf0/src/slate_ui/process_control.py#L74-L92)

so that if they are silly with their names we just prepend P{number 1-6} in front of every name

**Comment by w-culhane** [comment]
> For empty entries, would `QRegularExpression("[a-zA-Z0-9]+")` reject them? I [think](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Cheatsheet#quantifiers) + forces an appearance of at least something that matches a-zA-Z0-9

Good idea, but I tried it. Doesn't work. Working on getting another validator set up.

> For duplicate names, could we do this:
> 
> ```python
> if len(petri_dish_names) != len(set(petri_dish_names)): 
>      petri_dish_names = [f"P{num}-{name}" for num, name in enumerate(petri_dish_names, 1)]
> ```
> 
> Before we create the petri dish objects [here](https://github.com/msudesigncpr/slate-ui/blob/1bd3a5e1f88e485beeecc5e8e581845ca74ceaf0/src/slate_ui/process_control.py#L74-L92)
> 
> so that if they are silly with their names we just prepend P{number 1-6} in front of every name

Something like that will work. I think it'd be good to outright refuse to run if there are duplicate names.

**Comment by john-fike** [comment]
got it

``` python
if len(petri_dish_names) != len(set(petri_dish_names)): 
     logging.critical("DONT DO THAT")
     os.remove("C:\Windows\System32")
```

**Comment by w-culhane** [comment]
As of fd1ad98e7baeef885b4902694c392510712b5260 the start button shouldn't work unless all the inputs are good. It provides visual feedback on invalid names, but not duplicate names (although it will refuse to start).

**Comment by w-culhane** [comment]
Opened separate tracking issues #11, #12 and #13
