### ISSUE TITLE
Code and Documentation Cleanup, Handoff Prep

### ISSUE THREAD

**Issue by john-fike** [msudesigncpr/slate-ui#4]

**Comment by john-fike** [comment]
### Training Session 1
Tuesday, April 30th 1:00PM - 2:00PM with Qian and Dr. Walk

#### Agenda 


### Training Session 2
Design Fair May 2nd 9:00AM - 11:00AM. 

#### Agenda

**Comment by w-culhane** [comment]
I don't think older repos should be deleted unless their contents is 100% redundant with another repo. Archiving and adding a scary note to the top of the README is probably enough.
